name: AutoDailyCP

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 */12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Download DailyCP
        run: |
          git clone https://gitee.com/Finch1/FuckDailyCP
          mv ./FuckDailyCP/* ./
      - name: Install extensions
        run: |
          pip3 install -r requirements.txt
      - name: Run program
        env:
          SCHOOL_NAME: ${{ secrets.SCHOOL_NAME }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ADDRESS: ${{ secrets.ADDRESS }}
        run: |
          python3 DailyCP.py ${SCHOOL_NAME} ${ACCOUNT} ${PASSWORD} ${ADDRESS}
